default: &default
  adapter: postgresql
  host: localhost
  username: ubuntu
  password: password
  timeout: 5000
  template: template0
  
development:
  <<: *default
  database: app_development
test: &test
  <<: *default
  database: app_test
production:
  <<: *default
  database: app_production
  port: 5432

cucumber:
  <<: *test
